### ISSUE TITLE
Problem in OAuthTokenCredential.cs

### ISSUE THREAD

**Issue by JuVincent** [geoperez/PayPalCore#3] opened 2017-09-15 13:02 UTC
Hello
I had a problem with your package. It works fine on sandbox mode but not in live

The problem is in the constructor of OAuthTokenCredential class
`OAuthTokenCredential(string clientId = "", string clientSecret = "", Dictionary<string, string> config = null)`

the config param is never used when i pass it into constructor because the line 100 of this class is commented
`this.config = new Dictionary<string, string>();// config != null ? ConfigManager.GetConfigWithDefaults(config) : ConfigManager.GetConfigWithDefaults(ConfigManager.Instance.GetProperties());`

**Comment by geoperez** [comment] 2017-09-15 14:08
Hi,

Yes, the config manager is not ported yet. I'm kinda busy with other
projects so I'm not able to help you but any pull request is welcomed.

On Sep 15, 2017 8:02 AM, "JuVincent" <notifications@github.com> wrote:

Hello
I had a problem with your package. It works fine on sandbox mode but not in
live

The problem is in the constructor of OAuthTokenCredential class
OAuthTokenCredential(string clientId = "", string clientSecret = "",
Dictionary<string, string> config = null)

the config param is never used when i pass it into constructor because the
line 100 of this class is commented
this.config = new Dictionary<string, string>();// config != null ?
ConfigManager.GetConfigWithDefaults(config) : ConfigManager.
GetConfigWithDefaults(ConfigManager.Instance.GetProperties());

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/geoperez/PayPalCore/issues/3>, or mute the thread

**Comment by JeanCollas** [comment] 2017-09-16 10:38
Hi, you may check on this fork, you may find a bit of code to solve your issue:
https://github.com/JeanCollas/PayPal-NETStandard-SDK/
I am using a similar port on prod and it works well. 

The other option is to target .Net 2.0, there might be an implementation of this now.

**Comment by picobots** [comment] 2017-09-21 21:36
@JeanCollas Would you be willing to provide a very simple code snippet (or config file sample) that explains how use your library in a .NET Core project? I'm trying to just get a simple access token via the `OAuthTokenCredential` class using this code:

`var accessToken = new OAuthTokenCredential(myClientId, myClientSecret).GetAccessToken();`

And I immediately get an exception in LogConfiguration.cs:

`FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager`

**Comment by JeanCollas** [comment] 2017-09-24 17:28
My current csproj is the following:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyTitle>PayPalCore</AssemblyTitle>
    <AssemblyName>PayPalCore</AssemblyName>
    <PackageId>PayPalCore</PackageId>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="System.Collections.Specialized" Version="4.3.0" />
    <PackageReference Include="System.Net.Requests" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Extensions" Version="4.3.0" />
    <PackageReference Include="System.Security.Cryptography.Algorithms" Version="4.3.0" />
  </ItemGroup>

</Project>
```

In configureService, I have this:

            services.AddTransient<PayPalService, PayPalService>();

Followed by:

            IConfigurationSection ppSection;
            if (CurrentEnvironment.IsDevelopment())
            {
                ppSection = Configuration.GetSection("Dev:PayPal");
            }
            else
            { // Prod
                ppSection = Configuration.GetSection("PayPal");
            }
            var ppConf = new PaypalConfig();
            ppSection.Bind(ppConf);
            // method 1
            services.Configure<PaypalConfig>(o => ppSection.Bind(o));
            // method 2
            PayPal.Api.ConfigManager.Instance.SetConfig(ppConf.Mode, ppConf.ClientId, ppConf.ClientSecret);

I think 1 of the two initialization methods is not used, but I don't remember which one :) 

I will try to upload a sample

**Comment by JeanCollas** [comment] 2017-09-24 18:13
You can try to follow this, I think I have included most of the code except the actual call, but it is quite obvious as full methods are provided:
https://github.com/JeanCollas/PayPal-NETStandard-SDK/tree/Core/SamplesNetStandard

**Comment by mombrea** [comment] 2017-11-07 12:20
This should be fixed in pull request #4
https://github.com/geoperez/PayPalCore/pull/4

**Comment by kkagill** [comment] 2019-03-07 19:41
@mombrea I've tried but getting 401 unauthorized for live mode. Can anyone confirm that live mode is actually working?

**Comment by geoperez** [comment] 2019-03-07 19:54
@kkagill please check the official SDK: https://github.com/paypal/PayPal-net-SDK/tree/2.0-beta

**Closed as completed by geoperez** 2019-03-07 19:54 UTC
